---
# tasks file for yum-repo-setup
- name: Setup Docker CE stable repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    checksum: "sha256:6650718e0fe5202ae7618521f695d43a8bc051c539d7570f0edbfa5b4916f218"
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'