version: "3"

services:
  mongodb:
    image: mongo:3-xenial
    container_name: mongo
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      # admin authentication database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456Aa@
      - MONGO_INITDB_DATABASE=vimo-session
    ports:
      - 27018:27017
    volumes:
      - data:/data/db
      - ./init.d/:/docker-entrypoint-initdb.d/
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=mongo-express
      - ME_CONFIG_BASICAUTH_PASSWORD=123456Aa@
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123456Aa@
    ports:
      - 27019:8081

volumes:
  data:

networks:
  default:
    external:
      name: vimo
