version: "3"

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    container_name: logstash-${TAG}
    hostname: logstash.prod
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - LS_JAVA_OPTS=-Xmx4g -Xms2g
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./config:/usr/share/logstash/config
      - ./pipeline:/usr/share/logstash/config/pipeline
      - ./certs:/usr/share/logstash/config/certs
    ports:
      - "5045:5044"
      - "9601:9600"
    networks:
      default:
        aliases:
          - logstash.prod
    logging:
      options:
        max-size: '512m'
        max-file: '3'
      driver: json-file
    healthcheck:
      test: bin/logstash -t
      interval: 60s
      timeout: 50s
      retries: 5

networks:
  default:
    external:
      name: docker-prod