apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:8.6.0-community
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              memory: 2048Mi
              cpu: 2000m
          volumeMounts:
            - mountPath: "/opt/sonarqube/data/"
              name: sonar-data
            - mountPath: "/opt/sonarqube/extensions/"
              name: sonar-extensions
          env:
            - name: "SONARQUBE_JDBC_USERNAME"
              value: "postgres"
            - name: "SONARQUBE_JDBC_URL"
              value: "jdbc:postgresql://postgres:5432/sonarqube"
            - name: "SONARQUBE_JDBC_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 9000
              protocol: TCP

      volumes:
        - name: sonar-data
          persistentVolumeClaim:
            claimName: sonar-data
        - name: sonar-extensions
          persistentVolumeClaim:
            claimName: sonar-extensions
