apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
stringData:
  email-username: hieupv
  email-password: ult.zda1
  slack-token: xoxb-3386990018007-3402779366066-LJIt9cgpdyAXFf5jCTZ0ihTp
