apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  service.slack: |
    token: $slack-token
    username: hieupv
    icon: https://cncf-branding.netlify.app/img/projects/argo/icon/color/argo-icon-color.png
