version: "3"

services:
  mongodb:
    image: mongo:3-xenial
    container_name: mongo
    restart: always
    environment:
      - TZ=Asia/Ho_Chi_Minh
      # admin authentication database
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=background-service
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
      - ./init.d/:/docker-entrypoint-initdb.d/

volumes:
  data:
