# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end

  config.vm.define "postgre-01" do |postgres1|
    postgres1.vm.box = "centos/7"
    postgres1.vm.network "private_network", ip: "192.168.33.10"
    postgres1.ssh.forward_agent = true
  end

  config.vm.define "postgre-02" do |postgres2|
    postgres2.vm.box = "centos/7"
    postgres2.vm.network "private_network", ip: "192.168.33.11"
    postgres2.ssh.forward_agent = true
  end

  config.vm.define "postgre-03" do |postgres3|
    postgres3.vm.box = "centos/7"
    postgres3.vm.network "private_network", ip: "192.168.33.12"
    postgres3.ssh.forward_agent = true
    postgres3.vm.provision :ansible do |ansible|
      ansible.limit = 'all'
      ansible.playbook = "postgres.yml"
    end
  end

end
