#A node can only join a cluster when it shares its cluster.name with all the other nodes in the cluster.
# Make sure that you don’t reuse the same cluster names in different environments,
# otherwise you might end up with nodes joining the wrong cluster.
cluster.name: vimo-uat
# In order to form a cluster with nodes on other servers
network.host: elasticsearch.uat

discovery.type: single-node
xpack.security.enabled: true

xpack.security.http.ssl.enabled: true
xpack.security.transport.ssl.enabled: true

xpack.security.http.ssl.key: ${CERTS_DIR}/elasticsearch/elasticsearch-uat.key
xpack.security.http.ssl.certificate: ${CERTS_DIR}/elasticsearch/elasticsearch-uat.crt
xpack.security.http.ssl.certificate_authorities: ${CERTS_DIR}/ca/ca.crt
# xpack.security.transport.ssl.key: ${CERTS_DIR}/elasticsearch/elasticsearch-uat.key
# xpack.security.transport.ssl.certificate: ${CERTS_DIR}/elasticsearch/elasticsearch-uat.crt
# xpack.security.transport.ssl.certificate_authorities: ${CERTS_DIR}/ca/ca.crt

# Configure monitoring data of elastic stack
xpack.monitoring.collection.enabled: true
xpack.monitoring.collection.interval: 60s

path.repo: /usr/share/elasticsearch/backup/repository