version: "3.7"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: filebeat
    hostname: ${HOSTNAME:?err}
    user: root # for adding docker metadata to processors
    environment:
      - TZ=Asia/Ho_Chi_Minh
    command: --strict.perms=false -e  # -e flag to log to stderr and disable syslog/file output
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./inputs.d/:/usr/share/filebeat/inputs.d/:ro
      - /data/app/mpos-export/logs/mpos-export:/var/logs/mpos-export:ro
    logging:
      options:
        max-size: '256m'
        max-file: '3'
      driver: json-file
    healthcheck:
      test: filebeat test config
      interval: 30s
      timeout: 15s
      retries: 5