version: "3"

services:
  es-cert:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    hostname: elasticsearch.prod
    container_name: create_certs
    command: >
        bash -c '
          if [[ ! -f /certs/bundle.zip ]]; then
            bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
            unzip /certs/bundle.zip -d /usr/share/elasticsearch/config/certificates/certs; 
          fi;
          chown -R 1000:0 /certs
        '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes: ['.:/usr/share/elasticsearch/config/certificates']