version: "3"

services: 
    filebeat:
        image: docker.elastic.co/beats/filebeat:7.9.0
        container_name: filebeat-test
        volumes: 
            - ./filebeat/inputs.d:/usr/share/filebeat/inputs.d
            - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./log:/var/logs
        networks:
            - test-logstash

    logstash:
        image: docker.elastic.co/logstash/logstash:7.9.0
        container_name: logstash-test
        volumes: 
            - ./logstash/config:/usr/share/logstash/config
            - ./logstash/pipeline:/usr/share/logstash/config/pipeline
        networks:
            - test-logstash

networks:
    test-logstash: