---
version: '3.3'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.1
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: '10.1.121.56:39092'
networks:
  default:
    external:
      name: kafka-network
