---
- name: Gather the rpm package facts
  package_facts:
    manager: auto

- name: Stop docker daemon if running
  service:
    name: docker
    state: stopped
  when: "'docker' in ansible_facts.packages"

- name: Uninstall old Docker version
  yum:
    name: >
      docker, docker-client, docker-client-latest,
      docker-common, docker-latest, docker-latest-logrotate,
      docker-logrotate, docker-engine, docker-ce,
    state: absent

- name: Remove Docker data
  file:
    path: /var/lib/docker
    state: absent
  