---
- name: Install required packages
  yum:
    update_cache: yes
    name: "{{ docker_required_packages }}"
    state: latest

- name: Install Docker CE engine
  yum:
    update_cache: yes
    name: "{{ docker_ce_packages }}"
    state: present