stages:
  - deploy

deploy Helm chart:
  stage: deploy
  tags:
    - runner-150-16
  before_script:
    - docker login $HARBOR_URL -u $HARBOR_USERNAME -p $HARBOR_PASSWD
    - chmod +x version-enforce.sh
  script:
    - ./version-enforce.sh $CI_COMMIT_TAG
    - docker run --rm -v "$(pwd)":/chart -w /chart hub.saobang.vn/nextpay-common/helm-cli:$HELM_CLI_IMAGE_VER push . harbor-saobang
  only:
    refs:
      - tags