version: "3"

services:
  elastalert:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elastalert
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - home:/opt/elastalert
      - ./config/config.yml:/opt/elastalert/config.yml
      - ./rules:/opt/elastalert/rules
      - ./test_rules:/opt/elastalert/test_rules

volumes:
  home: