apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-next360-mongodb
  namespace: next360
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: glusterfs
  volumeMode: Filesystem