version: "3.7"
services:
  apm-server:
    image: docker.elastic.co/apm/apm-server:${TAG}
    container_name: apm-server
    hostname: ${HOSTNAME:?err}
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - 8200:8200
    command: --strict.perms=false -e # -e flag to log to stderr and disable syslog/file output
    volumes:
      - ./config/apm-server.yml:/usr/share/apm-server/apm-server.yml
      - ./certs:/etc/certs
    logging:
      options:
        max-size: '512m'
        max-file: '3'
      driver: json-file
    healthcheck:
      test: curl -s http://localhost:8200/healthcheck >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  default:
    external:
      name: vimo-uat-network