# List of inputs to fetch data.
filebeat.config.inputs:
  enabled: true
  path: /usr/share/filebeat/inputs.d/*.yml
  reload.enabled: true
  reload.period: 3s

output.kafka:
  # initial brokers for reading cluster metadata
  hosts: ["10.1.121.55:9092"]

  # message topic selection + partitioning
  topic: 'test-logstash'
  partition.round_robin:
    reachable_only: false

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000


logging.metrics.enabled: false