version: "3"

services: 
    prometheus:
        image: "prom/prometheus"
        container_name: prometheus
        volumes:
            - data:/prometheus
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
        container_name: prometheus

volumes: 
    data: