apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-extra-config
data:
  ilm.json: |
    {
      "policy": {
        "_meta": {
          "description": "used for metricbeats index",
          "project": {
            "name": "NextPay monitoring",
            "department": "DevOps"
          }
        },
        "phases" : {
          "hot" : {
            "actions" : {
              "rollover" : {
                "max_primary_shard_size" : "50gb",
                "max_age" : "30d"
              }
            }
          },
          "delete" : {
            "min_age" : "30d",
            "actions" : {
              "delete" : {
                "delete_searchable_snapshot" : true
              }
            }
          }
        }
      }
    }
