apiVersion: v1
kind: Service
metadata:
  name: logstash-1-http
spec:
  type: ClusterIP
  ports:
    - name: http-logstash-1
      port: 9600
      protocol: TCP
      targetPort: 9600
  selector:
    statefulset.kubernetes.io/pod-name: logstash-1