apiVersion: v1
kind: Service
metadata:
  name: logstash-0-beat
spec:
  type: NodePort
  ports:
    - name: logstash-0-beat
      port: 5044
      protocol: TCP
      targetPort: 5044
      nodePort: 30005
  selector:
    statefulset.kubernetes.io/pod-name: logstash-0