core-platform-front:
  services:
    global:
      imagePullSecrets: nextpay-harbor
      image:
        repository: hub.saobang.vn/nextpay/core-platform-front
      elasticApm:
        ELASTIC_APM_SERVER_URL: http://10.1.150.114:8200
        ELASTIC_APM_ENVIRONMENT: core-platform-front-dev
        ELASTIC_APM_ENABLED: true
        ELASTIC_APM_ENABLE_LOG_CORRELATION: true
    #***********************************************************************************************************************
    #npa-host-master
    npa-host-master:
      enabled: true
      image:
        name: npa-host-master
        tag: dev-02862b83
      service:
        type: ClusterIP
        specs:
          - port: 80
            containerPort: 80 # if omit, default to port <-- this is container's port
            name: http
            protocol: TCP #default to TCP protocol
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: npa-host-master.nextshop.dev
            servicePort: 80
            path: /
      configmap:
        #operation env
        ELASTIC_APM_SERVICE_NAME: npa-host-master
        ELASTIC_APM_APPLICATION_PACKAGES: vn.nextpay
        #application env
        SPRING_REDIS_PORT: 6379
        SPRING_REDIS_HOST: redis-common-master.common
        SPRING_PROFILES_ACTIVE: dev
        SPRING_DATA_URI: mongodb://dev:KKuKUBS1cQ2Q@10.1.150.40:27017/nextpay-config?authSource=admin
        SERVER_PORT: 80
        PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FEV2QzNHZWZ1RPNXUvOUFMaUpKRjF6UDlMNgpsVm1HU1dFZWN0ZWdsVHFZWDIySkx3aklrTmQySzBLVjUzTWVoY3J5dHlUR1FtdWYyZGQzMDl0Y2hBSGp0ZmV6Ck43Tkwzckcwek5ReDdBM3dJVi9IaDRlU0g4OWF1S2JJeFNxaWl2MFJ2a2ZYMmZ3N0ZDQzBlb0tsVWExM1NDb3oKZTJXNTJsaUZsU1M1RFRwT1d3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
        PRIVATE_KEY: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlDWFFJQkFBS0JnUURXZDM0dlZnVE81dS85QUxpSkpGMXpQOUw2bFZtR1NXRWVjdGVnbFRxWVgyMkpMd2pJCmtOZDJLMEtWNTNNZWhjcnl0eVRHUW11ZjJkZDMwOXRjaEFIanRmZXpON05MM3JHMHpOUXg3QTN3SVYvSGg0ZVMKSDg5YXVLYkl4U3FpaXYwUnZrZlgyZnc3RkNDMGVvS2xVYTEzU0NvemUyVzUybGlGbFNTNURUcE9Xd0lEQVFBQgpBb0dCQUpTVVJpUlBLSmVhb0dxY0JEeG1xQ00rOVZCTEJiR2x4cFhNcEJ3SkpvWUhucUFxcUtBaTBGSjZsKys0CllDV21OVHEvck1kNW5vd281RUNNMG0wZXV4c2NUYnFNYTdSa2RXaTB3VHMzR1ozL2tMYzV3RDdYSmV2UnRlMDMKMS9oZ0o4bTNwWXBvaTMzWndCeDFDQmJvQWhZYjZXQ0NhUG9hbm45ZVVZWlBJQW5oQWtFQStnWHVqSzRxM3FMZgo3eU5kRElGb0ZPNE5ZVEtOQTZ1dEVscTc2Wk9BZ2JwQWkyRHFrcVBPQXhrZkhQMHBqSXBnZmVWaC9RMGpXL0RJCnliVlJrVm84S3dKQkFOdVg5MlBqNkpaUkRiTTNrb2toVnVGN05reUVyd0Q0STRvSjg2VG9mUFJlclYxSXp4L0QKc3l4R1NYQWFQR1pNb0Z4K0FDUWo2VDFPZTdIZkRWc3JycEVDUUUwVjh4eXd2a3J5VUxTOFpIM3NrQmlUNU5Bbwo4ODFENnhLVG93ZzdFQTN2VE9Nc09HYUoxb1NpQkRPOTRrZVFpbnVHYzVXL3JUMDFtZEtHOHVVcnV3MENRUUMxCmVSRHBiQjk2bWVGSWlsUi9IeDQ5bVNWMmR2QnBUS2VTSEVkTnNSUVNuMnVGKy9XdnVuc0h5ODVFNW1tajRROWwKWUh1ZFlsQU9haDJ2RVRab2NlRUJBa0J2aHRVSUcxclQ4cnI3T0xCQytPZmUrNC93WDRUOFNvWnEzNVFwdEt1ZAp5bTJaT2ZJRit1UEQwOVBqV0R2VW1iR1ZJQUdaeTZuWCs1RVVXSFJPRHNpMAotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
        LOGGING_LEVEL: debug
        NPA_MAMP_APMN_URL: https://npa-mamp-apmn.nextshop.dev/api
        
    
    #***********************************************************************************************************************
    #npa-proxy-gateway
    npa-proxy-gateway:
      enabled: true
      image:
        name: npa-proxy-gateway
        tag: dev-b802d562
      service:
        type: ClusterIP
        specs:
          - port: 80
            containerPort: 80 # if omit, default to port <-- this is container's port
            name: http
            protocol: TCP #default to TCP protocol
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 1024Mi
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: npa-proxy-gateway.nextshop.dev
            servicePort: 80
            path: /
      configmap:
        #operation env
        ELASTIC_APM_SERVICE_NAME: npa-proxy-gateway
        ELASTIC_APM_APPLICATION_PACKAGES: vn.nextpay
        #application env
        SPRING_REDIS_PORT: 6379
        SPRING_REDIS_HOST: redis-common-master.common
        SPRING_PROFILES_ACTIVE: dev
        SERVER_PORT: 80
        PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FEV2QzNHZWZ1RPNXUvOUFMaUpKRjF6UDlMNgpsVm1HU1dFZWN0ZWdsVHFZWDIySkx3aklrTmQySzBLVjUzTWVoY3J5dHlUR1FtdWYyZGQzMDl0Y2hBSGp0ZmV6Ck43Tkwzckcwek5ReDdBM3dJVi9IaDRlU0g4OWF1S2JJeFNxaWl2MFJ2a2ZYMmZ3N0ZDQzBlb0tsVWExM1NDb3oKZTJXNTJsaUZsU1M1RFRwT1d3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
        NPA_HOST_MASTER_DOMAIN: https://npa-host-master.nextshop.dev
        LOG_LEVEL: debug
        TOKEN_INSIDE: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJOTk5OTkiLCJyb2xlcyI6WyJJTlNJREUiXSwiaXNzIjoiRkdfTUFOVUFMX0dFTl9UT0tFTl9EVU5HUFYiLCJpYXQiOjE1NjMyNjk5MDgsImV4cCI6NDcxNjg2OTkwOH0.ursjj3k-9tvgrl29Uu9J8iTHLcl-MEx5FhmuU4BhEugrwEsC9P4tY4Nu42SnfwWtdyDu4qKbt9NuIaJzgdBNfQ
        JWT_SECRET: 36c8dda71cc687a94c2bec6a51969c59
        PARTNER_SERVICE_DOMAIN: https://npa-nsh-partner.nextshop.dev
        CORE_API_GATEWAY_DOMAIN: https://api.nextshop.dev
    
    #***********************************************************************************************************************
    #npa-iam
    npa-iam:
      enabled: true
      image:
        name: npa-iam
        tag: dev-80365786
      service:
        type: ClusterIP
        specs:
          - port: 80
            containerPort: 80 # if omit, default to port <-- this is container's port
            name: http
            protocol: TCP #default to TCP protocol
      resources:
        limits:
          memory: 1024Mi
          cpu: 2000m
        requests:
          memory: 512Mi
          cpu: 250m
      ingress:
        enabled: true
        annotations: {}
        hosts:
          - host: npa-iam.nextshop.dev
            servicePort: 80
            path: /
      configmap:
        #operation env
        ELASTIC_APM_SERVICE_NAME: npa-iam
        ELASTIC_APM_APPLICATION_PACKAGES: vn.nextpay.iam
        #application env
        SPRING_PROFILES_ACTIVE: dev
        SERVER_PORT: 80
        MONGO_URI: "mongodb://dev:KKuKUBS1cQ2Q@10.1.150.40:27017/np-application-iam?authSource=admin"
        
    
    #***********************************************************************************************************************
    #npa-api-gateway
    npa-api-gateway:
      enabled: true
      image:
        name: npa-api-gateway
        tag: dev-fdfb951b
      service:
        type: ClusterIP
        specs:
          - port: 80
            containerPort: 80 # if omit, default to port <-- this is container's port
            name: http
            protocol: TCP #default to TCP protocol
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 250m
          memory: 512Mi
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "5m"
        hosts:
          - host: npa-api-gateway.nextshop.dev
            servicePort: 80
            path: /
      configmap:
        #operation env

        #application env
        S3_SECRET_ACCESS_KEY: t7sZ7X/g38QVZCkuLZDKWMlOYaM2xPYMS3lgZ+II
        S3_REGION: ap-southeast-1
        S3_BUCKET_NAME: nextpos-images-dev
        S3_ACCESS_KEY_ID: AKIAQ7SH2MVQXYYJDPOM
        MONGO_URI: "mongodb://dev:KKuKUBS1cQ2Q@10.1.150.40:27017/nextpay-gateway?authSource=admin"
        HTTP_PORT: 80
        CORE_GATEWAY_DOMAIN: https://api.nextshop.dev
        AUTHENTICATION_PUBLIC_KEY: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlHZk1BMEdDU3FHU0liM0RRRUJBUVVBQTRHTkFEQ0JpUUtCZ1FEV2QzNHZWZ1RPNXUvOUFMaUpKRjF6UDlMNgpsVm1HU1dFZWN0ZWdsVHFZWDIySkx3aklrTmQySzBLVjUzTWVoY3J5dHlUR1FtdWYyZGQzMDl0Y2hBSGp0ZmV6Ck43Tkwzckcwek5ReDdBM3dJVi9IaDRlU0g4OWF1S2JJeFNxaWl2MFJ2a2ZYMmZ3N0ZDQzBlb0tsVWExM1NDb3oKZTJXNTJsaUZsU1M1RFRwT1d3SURBUUFCCi0tLS0tRU5EIFBVQkxJQyBLRVktLS0tLQo=
      
      