apiVersion: v2
name: elk-stack
description: A Helm chart of ELK stack for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: "1.0"

dependencies:
  - name: es-master-node
    version: 0.1.0
    condition: es-master-node.enabled
  - name: es-data-node
    version: 0.1.0
    condition: es-data-node.enabled
  - name: kibana
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: kibana.enabled
  - name: logstash
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: logstash.enabled
  - name: metricbeat
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: metricbeat.enabled
  - name: filebeat
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: filebeat.enabled
  - name: apm-server
    version: 7.16.2
    repository: https://helm.elastic.co
    condition: apm-server.enabled
  - name: heartbeat
    version: 7.16.2
    repository: https://hub.saobang.vn/chartrepo/nextpay
    condition: heartbeat.enabled