version: "3"

services: 
    grafana:
        image: "grafana/grafana"
        container_name: grafana
        ports: 
            - 3000:3000
        volumes: 
            - data:/var/lib/grafana
        logging: 
            options:
                max-size: "512m"
                max-file: "1"

volumes: 
    data: