version: "3.7"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    container_name: kibana.uat
    hostname: kibana.uat
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./ssl:/usr/share/kibana/config/certs
    ports:
      - 5601:5601
    healthcheck:
      test: curl -s http://localhost:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  default:
    external:
      name: vimo-uat-network